baseurl: "/northendlab-jekyll" # the subpath of your site, e.g. /blog
url: "https://themefisher.github.io" # the base hostname & protocol for your site, e.g. http://example.com

title: Northendlab Jekyll | Personal Blog Template
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Build settings
plugins:
  - jekyll-sitemap

# Scss Directory
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor