########################### Navigation ###################################
menu:
  # main menu
  main:
  - {name: Home, url: '/'}
  - {name: contact, url: '/contact'}
  - {name: Projects, url: '/'}
  - {name: Blog, url: '/blog'}
  # - {name: Blogs, url: '/tools'}

##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

##########################
  
  # Footer menu
  footer:
  - {name: Home, url: '/'}
  - {name: Contact, url: '/contact'}
  - {name: Blog, url: '/Blog'}


######################### Default Parameters ###########################

# logo
logo : "https://avatars0.githubusercontent.com/u/32003795?s=40&v=4"
# meta data
author : "Akash Hadagali"
description : "This is meta description"
# google analitycs ID
google_analitycs_id : "" # your id
# contact form action
contact_form_action : "#" # contact form works with : https://formspree.io
# copyright
copyright : "Copyright &copy; 2020 Made with &#10084;&#65039; by [Akash Hadagali](https://www.linkedin.com/in/akashhadagali/) <br> Theme is taken from [Themefisher](https://github.com/themefisher/northendlab-jekyll)"

# preloader
preloader:
  enable : true
  preloader : "" # use png, jpg, svg or gif format

# search
search:
  enable : true

############################## Social Site ##########################
social:
  # - name : "facebook"
  #   icon : "ti-facebook" # themify icon pack https://themify.me/themify-icons
  #   link : "#"
    
  - name : "twitter"
    icon : "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
    link : "https://twitter.com/akashc777"

  - name : "github"
    icon : "ti-github" # themify icon pack https://themify.me/themify-icons
    link : "https://github.com/akashc777"

  - name : "linkedin"
    icon : "ti-linkedin" # themify icon pack https://themify.me/themify-icons
    link : "https://www.linkedin.com/in/akashhadagali/"