########################### Navigation ###################################
menu:
  # main menu
  main:
  - {name: Home, url: '/'}
  - {name: contact, url: '/contact'}
  - {name: Projects, url: '/projects'}
  - {name: Blog, url: '/blog'}
  - {name: About, url: '/about/akash-hadagali'}
  # - {name: Blogs, url: '/tools'}

##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

##########################
  
  # Footer menu
  footer:
  - {name: Home, url: '/'}
  - {name: contact, url: '/contact'}
  - {name: Projects, url: '/projects'}
  - {name: Blog, url: '/blog'}
  - {name: About, url: '/about/akash-hadagali'}


######################### Default Parameters ###########################

# logo
logo : "/assets/images/logo.svg"
# meta data
author : "Akash Hadagali"
description : "This is meta description"
# google analitycs ID
google_analitycs_id : "G-PEV0XKD8YF" # your id
# contact form action
contact_form_action : "https://formspree.io/f/xeqpkkbn" # contact form works with : https://formspree.io
# copyright
copyright : "Made with ![alt text](/assets/images/gif-heart.gif) by [Akash Hadagali](https://www.linkedin.com/in/akashhadagali/)"

# preloader
preloader:
  enable : true
  preloader : "" # use png, jpg, svg or gif format

# search
search:
  enable : true

############################## Social Site ##########################
social:
  # - name : "facebook"
  #   icon : "ti-facebook" # themify icon pack https://themify.me/themify-icons
  #   link : "#"
    
  - name : "twitter"
    icon : "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
    link : "https://twitter.com/akashc777"

  - name : "github"
    icon : "ti-github" # themify icon pack https://themify.me/themify-icons
    link : "https://github.com/akashc777"

  - name : "linkedin"
    icon : "ti-linkedin" # themify icon pack https://themify.me/themify-icons
    link : "https://www.linkedin.com/in/akashhadagali/"